kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: autoscaling-dati-semantic-lodview
  namespace: ndc-dev
spec:
  scaleTargetRef:
    kind: DeploymentConfig
    name: dati-semantic-lodview
    apiVersion: apps.openshift.io/v1
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80