kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: dati-semantic-lodview
  namespace: ndc-prod
  labels:
    application: dati-semantic-lodview
spec:
  lookupPolicy:
    local: false

