---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: dati-semantic-lodview
  namespace: ndc-test
  labels:
    application: dati-semantic-lodview
spec:
  # TODO: consider publishing this application
  #       on a separate domain, e.g. lod-ndc-dev...
  host: lod-ndc-test.apps.cloudpub.testedev.istat.it
  to:
    kind: Service
    name: dati-semantic-lodview
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None