services:
  # Run super-linter locally
  super-linter:
    image: ghcr.io/super-linter/super-linter:latest
    environment:
      - LOG_LEVEL=INFO #DEBUG
      - CREATE_LOG_FILE=true
      - RUN_LOCAL=true
      - DEFAULT_BRANCH=stefanone91-27-super-linter-kubeconform
      - IGNORE_GITIGNORED_FILES=true
      - KUBERNETES_KUBECONFORM_OPTIONS= -schema-location 'https://openshiftjsonschema.dev/v4.10-standalone{{ .StrictSuffix }}/{{ .ResourceKind }}{{.KindSuffix}}.json' -ignore-filename-pattern '(.git|.github)/*' -strict -summary
    volumes:
      - ./:/tmp/lint
