---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: dati-semantic-webvowl
  namespace: ndc-test
  labels:
    application: dati-semantic-webvowl
spec:
  host: webvowl-ndc-test.apps.cloudpub.testedev.istat.it
  to:
    kind: Service
    name: dati-semantic-webvowl
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None