---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dati-semantic-admin
  name: dati-semantic-admin
  namespace: ndc-prod
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dati-semantic-admin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dati-semantic-admin
      name: dati-semantic-admin
      annotations:
        wordpress-bootstrap-trigger: bootstrap-20260624-17-fee1b65
    spec:
      containers:
        - name: dati-semantic-admin
          image: ghcr.io/teamdigitale/dati-semantic-admin:20260624-17-fee1b65
          imagePullPolicy: Always
          env:
            - name: SERVER_FORWARD_HEADERS_STRATEGY
              value: framework
            - name: SERVER_SERVLET_SESSION_COOKIE_SECURE
              value: "true"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
              value: https://keycloak-ndc-prod.apps.cloudpub.istat.it/realms/ndc
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID
              value: ndc-admin-bff-client
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: admin-oauth-prod
                  key: client-secret
            - name: NDC_BACKEND_URL
              value: http://dati-semantic-backend:8080
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 768Mi
            requests:
              cpu: 100m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
