---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: autoscaling-dati-semantic-lode
  namespace: ndc-test
spec:
  scaleTargetRef:
    kind: Deployment
    name: dati-semantic-lode
    apiVersion: apps.openshift.io/v1
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80