---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: dati-semantic-lode
  name: dati-semantic-lode
  namespace: ndc-prod
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dati-semantic-lode
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dati-semantic-lode
      name: dati-semantic-lode
    spec:
      containers:
        - env:
            - name: EXTERNAL_URL
              value: "/lode"
            - name: WEBVOWL_URL
              value: "/webvowl/#iri="
          image: ghcr.io/teamdigitale/dati-semantic-lode:20230210-21-f8d6926
          imagePullPolicy: Always
          name: dati-semantic-lode
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 800m
              memory: 2048Mi
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 75
