---
kind: Service
apiVersion: v1
metadata:
  name: keycloak
  namespace: ndc-prod
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  sessionAffinity: None
