kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: dati-semantic-ontology-ai-assistant
  namespace: ndc-dev
  labels:
    application: dati-semantic-ontology-ai-assistant
spec:
  lookupPolicy:
    local: false