kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: dati-semantic-schema-editor-api
  namespace: ndc-dev
  labels:
    application: dati-semantic-schema-editor-api
spec:
  host: schema-editor-api-ndc-dev.apps.cloudpub.testedev.istat.it
  path: /semantic-tool
  to:
    kind: Service
    name: dati-semantic-schema-editor-api
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
status: {}
