name: Test development infrastructure.

on:
    schedule:
      - cron: '30 * * * *'
    workflow_dispatch:

jobs:
  test_infrastructure_dev:
    runs-on: ubuntu-latest
    name: Test the infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Run tests.
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests
          pytest -v

